[package]
name = "rileyseaburg_website"
version = "0.1.0"
authors = ["RustyRoad"]
edition = "2021"

[dependencies]
actix-web = { version = "4.0.0-beta.8", features = ["openssl"] }
actix-files = "0.6.2"
actix-session = {version = "0.7.2", features = ["cookie-session"]}
actix-service = "2.0.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
random-string = "1.0.0"
env_logger = "0.10.0"
local-ip-address = "0.5.0"
futures = "0.3.23"
tera = "1.17.1"
reqwest = "0.11"
rustyroad = "0.1.7"
rand = "0.8.5"
chrono = "0.4.24"
base64 = "0.21.0"
dotenv = "0.15.0"
bcrypt = "0.14.0"
pin-project-lite = "0.2.10"
actix-identity = "0.5.2"
openssl = "0.10.55"
log = "0.4.19"
[dependencies.sqlx]
features = ["postgres", "macros", "chrono", "json", "uuid", "offline"]
version = "0.6.2"
