apiVersion: apps/v1
kind: Deployment
metadata:
  name: rileyseaburg-website
  namespace: rileyseaburg-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rileyseaburg-website
  template:
    metadata:
      labels:
        app: rileyseaburg-website
    spec:
      containers:
      - name: rileyseaburg-website
        image: rileyseaburg/website:0.0.1-alpha-0.0.5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rileyseaburg-service
  namespace: rileyseaburg-website
spec:
  selector:
    app: rileyseaburg-website
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rs-ingress
  namespace: rileyseaburg-website
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  rules:
  - host: rileyseaburg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rileyseaburg-service
            port:
              name: http
  - host: rileyseaburg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rileyseaburg-service
            port:
              name: https
  tls:
  - hosts:
    - rileyseaburg.com
    secretName: rs-tls-secret