[database]
name = "rileyseaburg_website"
database_name = "rileyseaburg_website"
database_user = "postgres"
database_password = "postgres"
database_host = "192.168.50.70"
database_port = "5432"
database_type = "postgres"