[database]
name = "rileyseaburg_website"
database_name = "rileyseaburg_db"
database_user = "postgres"
database_password = "postgres"
database_host = "127.0.0.1"
database_port = "5432"
database_type = "postgres"